# Generated by Django 5.2.8 on 2025-11-21 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acervo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colecionador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('ANIMAL', 'Animal'), ('VEGETAL', 'Vegetal'), ('MINERAL', 'Mineral'), ('OUTRO', 'Outro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colecao', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_registro_sistema', models.DateTimeField(auto_now_add=True)),
                ('colecionador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.colecionador')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('datacao', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_conservacao', models.CharField(choices=[('BOM', 'Bom'), ('REGULAR', 'Regular'), ('FRAGMENTADO', 'Fragmentado')], max_length=50)),
                ('dimensoes', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('inteireza', models.CharField(choices=[('INTEIRO', 'Inteiro'), ('PARCIAL', 'Parcial'), ('FRAGMENTADO', 'Fragmentado')], max_length=50)),
                ('observacoes_curadoria', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('acervo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.acervo')),
                ('categoria_acervo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.categoriaacervo')),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.colecao')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_criados', to=settings.AUTH_USER_MODEL)),
                ('imagem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image')),
                ('localizacao_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.localizacao')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.materiaprima')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimento', models.CharField(choices=[('INTERNO', 'Movimentação Interna'), ('SAIDA_EXTERNA', 'Saída Externa / Empréstimo')], max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='backend.item')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='backend.localizacao')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='backend.localizacao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubtipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='backend.materiaprima')),
            ],
            options={
                'unique_together': {('materia_prima', 'termo')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subtipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.subtipomaterial'),
        ),
    ]
