# Generated by Django 5.2.8 on 2025-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colecao',
            old_name='data_registro_sistema',
            new_name='data_registro',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_movimento',
            field=models.CharField(choices=[('INTERNO', 'Movimentação Interna'), ('EXTERNA', 'Saída Externa / Empréstimo')], max_length=50),
        ),
    ]
