# Generated by Django 5.2.8 on 2025-11-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_data_registro_sistema_colecao_data_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaacervo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
