# Generated by Django 5.2.8 on 2025-12-07 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_item_imagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimento', models.CharField(choices=[('INTERNO', 'Movimentação interna'), ('EXTERNA', 'Saída externa / Empréstimo')], max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='backend.item')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_destino', to='backend.localizacao')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_origem', to='backend.localizacao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
