# Generated by Django 5.2.8 on 2025-12-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_colecionador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='itens/'),
        ),
    ]
