# Generated by Django 5.2.8 on 2025-12-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='colecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.colecao'),
        ),
    ]
