from .acervo import AcervoSerializer
from .colecionador import ColecionadorSerializer
from .categoria_acervo import CategoriaAcervoSerializer
from .colecao import ColecaoSerializer
from .item_acervo import ItemAcervoSerializer
from .localizacao import LocalizacaoSerializer
from .materia_prima import MateriaPrimaSerializer
from .sub_tipo import SubTipoSerializer
from .reserva import ReservaSerializer